# Generated by Django 6.0.4 on 2026-04-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practico1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clima',
            name='nombre_ciudad',
        ),
        migrations.AddField(
            model_name='clima',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clima',
            name='ciudad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='practico1.ciudad'),
        ),
    ]
